### ISSUE TITLE
Missing ts-node

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#5]
When running the repository I get:
```

> @lionweb/repository@0.1.0 dev
> nodemon build/server.js

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node build/server.js src/server.ts`
sh: ts-node: command not found
[nodemon] failed to start process, "ts-node" exec not found
[nodemon] Error
    at Bus.<anonymous> (/Users/ftomassetti/repos/lionweb-repository/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:525:35)
    at ChildProcess.<anonymous> (/Users/ftomassetti/repos/lionweb-repository/node_modules/nodemon/lib/monitor/run.js:199:11)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

In #2 I previously added `ts-node` as a dev dependency, but I think it was later removed.
Was that removed on purpose?
Should we re-add it?

**Comment by joswarmer** [comment]
I removed ts-node as I was not using it anymore. However, `nodemon` is using ts-node in the background, so yes, I will add ts-node to the dependencies again.

**Comment by joswarmer** [comment]
Fixed in features/reference-changes
