### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#64]
When I update to the latest commit and run `npm install` that fails:
```
85 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@lionweb%2frepository-common - Not found              │
85 verbose stack     at /usr/share/nodejs/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15                               │
85 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                      │
85 verbose stack     at async RegistryFetcher.packument (/usr/share/nodejs/pacote/lib/registry.js:85:19)                                │
85 verbose stack     at async RegistryFetcher.manifest (/usr/share/nodejs/pacote/lib/registry.js:116:23)                                │
85 verbose stack     at async [nodeFromEdge] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1058:19)              │
85 verbose stack     at async [buildDepStep] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:928:11)               │
85 verbose stack     at async Arborist.buildIdealTree (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:206:7)       │
85 verbose stack     at async Promise.all (index 1)                                                                                     │
85 verbose stack     at async Arborist.reify (/usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:156:5)                           │
85 verbose stack     at async Install.exec (/usr/share/nodejs/npm/lib/commands/install.js:146:5)
```

If I go back a few commits(`git checkout 988b48d2955e341083f18df692d1036b2cb596ff`) and run the same command it succeeds.

**Comment by joswarmer** [comment]
I forgot to push some changes, it should work again now after you update the main branch.

**Comment by joswarmer** [comment]
I am checking whether there is more to be done.  Strangely, I get no errors on npm install.

**Comment by joswarmer** [comment]
Ok, can you try again? There were some version numbers and dependencies mixed up.

**Comment by ftomassetti** [comment]
I confirm it works now. Thank you!
