### ISSUE TITLE
Invalid string length when producing answer to /bulk/retrieve

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#66]
With a recent version of the repository, on a new machine, I get this error, which I was not getting before:
```
Exception while serving request for /bulk/retrieve?depthLimit=99: Invalid string length                                                 
RangeError: Invalid string length                                                                                               
    at JSON.stringify (<anonymous>)                                                                                                    
    at stringify (/home/cis/repos/lionweb-repository/node_modules/express/lib/response.js:1150:12)                                     
    at ServerResponse.json (/home/cis/repos/lionweb-repository/node_modules/express/lib/response.js:271:14)                            
    at ServerResponse.send (/home/cis/repos/lionweb-repository/node_modules/express/lib/response.js:162:21)                            
    at lionwebResponse (file:///home/cis/repos/lionweb-repository/packages/common/dist/apiutil/LionwebResponse.js:11:14)               
    at retrieve (file:///home/cis/repos/lionweb-repository/packages/bulkapi/dist/controllers/BulkApi.js:178:13)                        
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                      
    at async file:///home/cis/repos/lionweb-repository/packages/common/dist/apiutil/functions.js:159:13
```

We may explore stream serialization, for example using `JSONStream`

**Comment by joswarmer** [comment]
The invalid string length means that the retrieve string is too long?

**Comment by dslmeinte** [comment]
We've seen this one before, I think. Let me search for a bit.

**Comment by dslmeinte** [comment]
There was #49 . I thought we remedied that already by only using `JSON.stringify` in batches. Why is that not enough? Should the batch size be 1?

**Comment by ftomassetti** [comment]
> There was https://github.com/LionWeb-io/lionweb-repository/issues/49 . I thought we remedied that already by only using JSON.stringify in batches.
In https://github.com/LionWeb-io/lionweb-repository/pull/50 we manually built `JSON.stringify` on individual elements and then built a JSON in a stream. It was a manual process applied to a couple of requests. Now we are seeing a similar problem in another request. We could solve it in the same way, but it would be invasive and error prone, while using a library that does what `JSON.stringify` does but on a stream, could be simpler, more robust, and easily applicable to all responses
